AAA_NOTES: Remove EFDMix in ResNet network || Changed mstcn_layers from 16 to 8
job_name: FALL-NO-MIX

seed: 1

# Paras for training feature embedding
label_dir: /research/dept8/rshr/jfcao/Dataset/ESD_new_data/TemData/ClinicalTrialGT
data_file: /uac/rshr/jfcao/local/ProjectCode/ProcessedDataset/DATA_DICT_MERGE.pkl
sample_weights: [1.0, 1.0, 1.0, 1.0]
# [0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, 25, 26, 27, 28, 30, 31, 32, 33, 35, 36, 37, 38, 40, 41]
#train_names: [22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 36, 37, 38, 39, 41, 42, 43, 44]
train_names: []
# [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
val_names: [0, 1, 2, 3]
test_names: [0, 1, 2, 3]
num_worker: 16

## ResNet parameters
out_classes: 4
class_weights: [0.04837749281514583, 0.5400151879633762, 0.24252126473837363, 0.16908605448310432]
start_iter: none
resnet_lr: 5e-4
resnet_momentum: 0.9
resnet_weight_decay: 0  # 2022-25-14-17-44
resnet_iterations: 8000
resnet_train_bs: 128
resnet_decay_steps: [6000]
save_model: /uac/rshr/jfcao/local/ProjectCode/Robot/ESDSafety/runs
resnet_model: /uac/rshr/jfcao/local/ProjectCode/Robot/ESDSafety/runs/resnet50_2022-20-19-35-33_last.pth
emb_file: /research/dept8/rshr/jfcao/ProjectCode/ProcessedDataset/emb_ESDSafety2022-03-12-35-42.pkl


## Fusion-transformer parametres
mstcn_stages: 2
mstcn_layers: 8  # Changed
mstcn_f_maps: 32
mstcn_f_dim: 2048
mstcn_causal_conv: True
seq: 1024
fusion_iter: none
fusion_model: /uac/rshr/jfcao/local/ProjectCode/Robot/ESDSafety/runs/fusion_2022-20-19-35-33.pth

trans_lr: 1e-2
trans_weight_decay: 5e-3
trans_iterations: 4000
trans_steps: [1500, 2500]
trans_seq: 30
trans_bs: 1
trans_model: /uac/rshr/jfcao/local/ProjectCode/Robot/ESDSafety/runs/transformer_2022-20-19-35-33.pth
pred_folder: /uac/rshr/jfcao/local/ProjectCode/Robot/ESDSafety/results
Histogram: /research/dept8/rshr/jfcao/ProjectCode/ProcessedDataset/VideoSample
trans_iter: none